import {useEffect,useState} from 'react'
import {createAlert,osmContext,satelliteContext,getHistory} from '../api'
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts'
export default function DetailPanel({selected,onToast}){
 const [osm,setOsm]=useState(null),[sat,setSat]=useState(null),[history,setHistory]=useState([]),[busy,setBusy]=useState(false)
 useEffect(()=>{setOsm(null);setSat(null);setHistory([]); if(selected?.hotspot_id?.startsWith('LIVE-')) getHistory(selected.hotspot_id).then(setHistory).catch(()=>{})},[selected])
 if(!selected)return <aside className="detail empty-detail"><div className="empty-icon">◎</div><h3>Select a thermal event</h3><p>Click a hotspot on the map or priority queue to inspect its evidence, context and recommended action.</p></aside>
 const alertIt=async()=>{try{setBusy(true);await createAlert({hotspot_id:selected.hotspot_id,severity:selected.risk_level,message:`${selected.classification.replaceAll('_',' ')} detected near ${selected.facility_name||'unknown facility'}; risk score ${selected.risk_score}/100. Verify with operational sources.`,facility_name:selected.facility_name});onToast('Alert created successfully')}catch(e){onToast(e.message)}finally{setBusy(false)}}
 const enrichOSM=async()=>{try{setBusy(true);setOsm(await osmContext({latitude:selected.latitude,longitude:selected.longitude,radius_m:2500}))}catch(e){onToast(e.message)}finally{setBusy(false)}}
 const enrichSat=async()=>{try{setBusy(true);setSat(await satelliteContext(selected.latitude,selected.longitude))}catch(e){onToast(e.message)}finally{setBusy(false)}}
 return <aside className="detail"><div className="detail-head"><div><span className={`risk-badge ${selected.risk_level.toLowerCase()}`}>{selected.risk_level} · {Number(selected.risk_score).toFixed(0)}</span><h2>{selected.hotspot_id}</h2><p>{selected.classification.replaceAll('_',' ')}</p></div><span className="source-badge">{selected.data_mode||'DEMO'}</span></div><div className="method-line">Decision method: <b>{selected.classification_method||"ml"}</b></div><div className="detail-grid">{[['FRP',`${Number(selected.frp).toFixed(1)} MW`],['TI4',`${Number(selected.bright_ti4).toFixed(1)} K`],['Confidence',`${Math.round(Number(selected.confidence_score)*100)}%`],['Persistence',`${Math.round(Number(selected.persistence_30d)*100)}%`],['Industrial distance',`${Math.round(Number(selected.industrial_distance_m))} m`],['30d detections',selected.detections_30d],['FRP anomaly',`${Number(selected.frp_anomaly_ratio).toFixed(1)}×`],['Facility',selected.facility_name||'None']].map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><div className="evidence-actions"><button onClick={enrichOSM} disabled={busy}>Inspect OSM context</button><button onClick={enrichSat} disabled={busy}>Inspect satellite</button><button className="primary" onClick={alertIt} disabled={busy}>Create alert</button></div>{osm&&<div className="evidence-box"><b>OSM context</b><span>{osm.count} nearby mapped elements</span><small>{osm.types?.slice(0,5).join(' · ')||'No industrial tags found'}</small></div>}{sat&&<div className="evidence-box"><b>Satellite adapter</b><span>{sat.status} · {sat.items??0} candidate scenes</span><small>{sat.message||'Scene search completed; pixel indices require configured raster extraction.'}</small></div>}{history.length>1&&<div className="history"><div className="section-title">30-day local FRP history</div><ResponsiveContainer width="100%" height={160}><LineChart data={history}><XAxis dataKey="date" hide/><YAxis width={35}/><Tooltip/><Line type="monotone" dataKey="frp" dot={false}/></LineChart></ResponsiveContainer></div>}<div className="explain"><div className="section-title">Decision evidence</div><div className="bar"><span>Thermal intensity</span><i><em style={{width:`${Math.min(100,Number(selected.frp)/2)}%`}}/></i></div><div className="bar"><span>Industrial context</span><i><em style={{width:`${selected.industrial_context?100:0}%`}}/></i></div><div className="bar"><span>FRP anomaly</span><i><em style={{width:`${Math.min(100,Number(selected.frp_anomaly_ratio)*20)}%`}}/></i></div><div className="bar"><span>FIRMS confidence</span><i><em style={{width:`${Number(selected.confidence_score)*100}%`}}/></i></div></div></aside>
}
